# Generated by Django 2.2.7 on 2019-11-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mass', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=2048)),
            ],
        ),
    ]
