# Generated by Django 2.2.7 on 2019-11-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='age',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mass',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='radius',
            field=models.CharField(max_length=150),
        ),
    ]
