# Generated by Django 2.2.7 on 2019-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191107_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialbody',
            name='body_type',
            field=models.CharField(choices=[('TP', 'Terrestrial Planets'), ('GG', 'Gas Giants'), ('IG', 'Ice Giants'), ('DP', 'Dwarf Planets')], default='TP', max_length=2),
            preserve_default=False,
        ),
    ]
