# Generated by Django 2.2.7 on 2019-11-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_celestialbody_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='mass',
            field=models.FloatField(),
        ),
    ]
