# Generated by Django 2.2.7 on 2019-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191110_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='body_type',
            field=models.CharField(choices=[('S', 'Star'), ('M', 'Moon'), ('TP', 'Terrestrial Planets'), ('GG', 'Gas Giants'), ('IG', 'Ice Giants'), ('DP', 'Dwarf Planets')], max_length=2),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='radius',
            field=models.FloatField(),
        ),
    ]
