# Generated by Django 2.2.7 on 2019-11-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
